# Generated by Django 3.0.1 on 2019-12-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('emp_id', models.IntegerField()),
                ('Companyname', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('City', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=10)),
                ('Zip', models.IntegerField()),
                ('Email', models.CharField(max_length=10)),
                ('Web', models.CharField(max_length=10)),
            ],
        ),
    ]
